### ISSUE TITLE
UI does not respond to size changes well

### ISSUE THREAD

**Issue by heftymouse** [HEIC-to-JPEG-Dev/DuplicateFileCleanerPlusPlus#3] opened 2022-11-26 05:04 UTC
If the app window's size is changed while scanning, the existing UI just scales up to the new width, leaving a lot of empty space. In the duplicate selection screen, if the window is restored to a small size, the UI elements clip into each other.

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-11-28 08:13
Known bug in WinUI core code - this can't be fixed until WinUI is fixed:
https://github.com/microsoft/microsoft-ui-xaml/issues/7628

**Comment by heftymouse** [comment] 2022-11-28 17:55
This could be solved by switching to the AppSDK titlebar, it even works downlevel as of 1.2.0

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-11-29 08:47
I'll investigate further as the titlebar is currently controlled through WinUIex

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-12-02 10:17
Moving from WinUIex to AppSDK titlebar is complex due to the imaturity of WinUI (there are currently 3 ways to do the same thing). Microsoft have confirmed this will all be merged into a new common API (probably SDK 1.3) - when this is complete, it will be implemented into app to enhance the Window control.

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-12-05 12:36
The next release will have the updated code to resolve this. It now uses the AppSDK directly and no longer uses WinUIex. this gets round the bug in WinUI and using ExtendsClientIntoTitleBar - I'll mark this as resolved when I release.

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-12-07 08:15
Resolved with release 1.3

**Closed by HEIC-to-JPEG-Dev** 2022-12-07 08:15 UTC
Labels: enhancement
